[workspace]
members = ["projects/*"]
default-members = [
    "projects/sm-ast",
    "projects/sm-parser",
    "projects/sm-playground",
    "projects/sm-wrapper",
]
exclude = [
    "projects/.DS_Store",
    "projects/sm-std",
    "projects/sm-book",
]

[profile.release]
lto = true
